### ISSUE TITLE
'Content-Type is unavailable' error?

### ISSUE THREAD

**Issue by pauricthelodger** [trevorpower/hackerspaces-status-wall#1]
Howdy Trevor,

Line 68-72 on main.coffee has Content-Type parsey bits. I think that's the part that doesn't seem to be reading correctly!

091 Labs is definitely sending a Content-Type header since earlier today anyway but I don't know enough of (coffee || java)script to figure out the error.

If I can be of help, let me know!

Cheers,
Padraic

**Comment by trevorpower** [comment]
Hi Padraic,

I seems to be working fine on Chrome for me, if you tell me where you are seeing the problem I will have a look.

**Comment by pauricthelodger** [comment]
Hmm.. yeah, I just checked hackerspaces.me/wall in Chrome and it doesn't say anything there.

In Firefox, it says "Content-Type is unavailable" for almost all spaces.

Running Ubuntu 12.04 with Firefox 13!

**Comment by trevorpower** [comment]
Yeah, I'm aware of some issues with other browsers. Was meant to come back to those. Will make an effort to address them soon.

Thanks for the feedback.

**Comment by trevorpower** [comment]
As far as I can tell, Firefox hides the content type for cross domain requests. As far as the client side code can tell it isn't set, so I will close this issue.

I will be changing the architecture soon, so so that all requests go through the proxy, then the API status info will not be dependent on browser behavior.
